spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///crawler?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ckj

  jpa:
    database: MySQL
    show-sql: false
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
